-- 主键字段统一用CHAR(36)
-- 商品分类表
CREATE TABLE
IF
	NOT EXISTS `TB_SORTS` ( `sortid` CHAR ( 36 ), `sortname` VARCHAR ( 10 ) NOT NULL, PRIMARY KEY ( `sortid` ) ) ENGINE = INNODB DEFAULT CHARSET = utf8;
	
	-- 商品表
CREATE TABLE
IF
	NOT EXISTS `TB_COMMODITY` (
	`comid` CHAR ( 36 ),
	`comname` VARCHAR ( 50 ),
	`price` DECIMAL ( 10, 0 ),
	`inventory` INT,
	`picture` VARCHAR ( 200 ),
	`describe` VARCHAR ( 200 ),
	`sortid` CHAR ( 36 ),
	PRIMARY KEY ( `comid` ) 
	) ENGINE = INNODB DEFAULT CHARSET = utf8;
ALTER TABLE TB_COMMODITY ADD CONSTRAINT FK_SORTID FOREIGN KEY ( SORTID ) REFERENCES TB_SORTS ( SORTID );


-- 用户信息表
CREATE TABLE
IF
	NOT EXISTS `TB_USERINFO` (
	`userid` CHAR ( 36 ),
	`password` CHAR ( 20 ),
	`sign` CHAR ( 1 ),
	`email` VARCHAR ( 20 ),
	`realname` VARCHAR ( 10 ),
	`nickname` VARCHAR ( 10 ),
	`idnumber` VARCHAR ( 10 ),
	`sex` VARCHAR ( 1 ),
	`telephone` VARCHAR ( 13 ),
	`birthday` DATE,
	PRIMARY KEY ( `userid` ) 
	) ENGINE = INNODB DEFAULT CHARSET = utf8;
	
	
	-- 评论表
CREATE TABLE
IF
	NOT EXISTS `TB_COMMENT` (
	`commentid` CHAR ( 36 ),
	`content` VARCHAR ( 200 ),
	`username` VARCHAR ( 10 ),
	`createdate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`comid` CHAR ( 36 ) NOT NULL,
	`userid` CHAR ( 36 ) NOT NULL,
	PRIMARY KEY ( `commentid` ) 
	) ENGINE = INNODB DEFAULT CHARSET = utf8;
ALTER TABLE TB_COMMENT ADD CONSTRAINT FK_COMID FOREIGN KEY ( COMID ) REFERENCES TB_COMMODITY ( COMID );
ALTER TABLE TB_COMMENT ADD CONSTRAINT FK_COMMENT_USERID FOREIGN KEY ( USERID ) REFERENCES TB_USERINFO ( USERID );

-- 收货地址表
CREATE TABLE
IF
	NOT EXISTS `TB_SHIPADDRESS` (
	`addressid` CHAR ( 36 ) NOT NULL,
	`userid` CHAR ( 36 ) NOT NULL,
	`receiverperson` VARCHAR ( 10 ) NOT NULL,
	`shiptelephone` VARCHAR ( 200 ),
	`location` VARCHAR ( 200 ),
	`detailaddress` VARCHAR ( 200 ),
	`sign` CHAR ( 1 ),
	PRIMARY KEY ( `addressid` ) 
	) ENGINE = INNODB DEFAULT CHARSET = utf8;
ALTER TABLE TB_SHIPADDRESS ADD CONSTRAINT FK_USERID FOREIGN KEY ( USERID ) REFERENCES TB_USERINFO ( USERID );


-- 订单表
CREATE TABLE
IF
	NOT EXISTS `TB_ORDER` (
	`orderid` CHAR ( 36 ) NOT NULL,
	`transtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`userid` CHAR ( 36 ) NOT NULL,
	`orderstatus` CHAR ( 1 ) NOT NULL,
	`userwords` VARCHAR ( 100 ),
	`addressid` CHAR ( 36 ),
	`total` DECIMAL ( 10, 0 ),
	PRIMARY KEY ( `orderid` ) 
	) ENGINE = INNODB DEFAULT CHARSET = utf8;
ALTER TABLE TB_ORDER ADD CONSTRAINT FK_ORDER_ADDRESSID FOREIGN KEY ( ADDRESSID ) REFERENCES TB_SHIPADDRESS ( ADDRESSID );
ALTER TABLE TB_ORDER ADD CONSTRAINT FK_ORDER_USERID FOREIGN KEY ( USERID ) REFERENCES TB_USERINFO ( USERID );


-- 商品明细表
CREATE TABLE
IF
	NOT EXISTS `TB_ORDERDETAIL` (
	`detailid` CHAR ( 36 ) NOT NULL,
	`orderid` CHAR ( 36 ) NOT NULL,
	`comid` CHAR ( 36 ) NOT NULL,
	`comcount` INT ( 3 ) NOT NULL,
	PRIMARY KEY ( `detailid` ) 
	) ENGINE = INNODB DEFAULT CHARSET = utf8;
ALTER TABLE TB_ORDERDETAIL ADD CONSTRAINT FK_DETAIL_COMID FOREIGN KEY ( COMID ) REFERENCES TB_COMMODITY ( COMID );
ALTER TABLE TB_ORDERDETAIL ADD CONSTRAINT FK_ORDERID FOREIGN KEY ( ORDERID ) REFERENCES TB_ORDER ( ORDERID );

-- 购物车表
CREATE TABLE
IF
	NOT EXISTS `TB_SHOPCART` (
	`shopcartid` CHAR ( 36 ) NOT NULL,
	`comid` CHAR ( 36 ) NOT NULL,
	`comcount` INT ( 3 ) NOT NULL,
	`userid` CHAR ( 36 ) NOT NULL,
	PRIMARY KEY ( `shopcartid` ) 
	) ENGINE = INNODB DEFAULT CHARSET = utf8;
ALTER TABLE TB_SHOPCART ADD CONSTRAINT FK_SHOPCART_COMID FOREIGN KEY ( COMID ) REFERENCES TB_COMMODITY ( COMID );
ALTER TABLE TB_SHOPCART ADD CONSTRAINT FK_SHOPCART_USERID FOREIGN KEY ( USERID ) REFERENCES TB_USERINFO ( USERID );